### PR TITLE
non-interactive SSH run - fixes #19

### LINKED ISSUE #19: non-interactive SSH run
I've set vertx-shell to connect with SSH, and everything works very well.

The only problem is, how to do non-interactive things vis ``ssh`` command?

I've tried:

    ssh user@${ip} -p ${port} ls

But I failed.

### PR DESCRIPTION
**Pull request by vietj**
please review @cescoffier @pmlopes

### CODE REVIEW

File: src/main/java/io/vertx/ext/shell/impl/ShellServerImpl.java [hunk 1]
```diff
@@ -167,6 +170,39 @@ public ShellServer listen(Handler<AsyncResult<Void>> listenHandler) {
...
+            public Tty stdinHandler(Handler<String> handler) {
+              return this;
+            }
+            @Override
+            public Tty write(String data) {
+              return this;
+            }
+            @Override
+            public Tty resizehandler(Handler<Void> handler) {
+              return null;
```
Comment (tsegismont) [inline src/main/java/io/vertx/ext/shell/impl/ShellServerImpl.java]: Why return null here and this in other methods returning the Tty ?

File: src/main/java/io/vertx/ext/shell/term/impl/ExecCommand.java [hunk 2]
```diff
@@ -0,0 +1,89 @@
...
+    exitCallback.onExit(status);
+  }
+
+  @Override public void setExitCallback(ExitCallback callback) {
+    this.exitCallback = callback;
+  }
+
+  @Override public void setInputStream(InputStream in) {}
+  @Override public void setOutputStream(OutputStream out) {}
+  @Override public void setErrorStream(OutputStream err) {}
```
Comment (tsegismont) [inline src/main/java/io/vertx/ext/shell/term/impl/ExecCommand.java]: I am wondering how command input/output works. I see here that callbacks are no-op, and the special Tty impl does nothing either (simply return `this`)

**Comment by tsegismont** [comment]
Couple of questions inline but LGTM otherwise

File: src/main/java/io/vertx/ext/shell/impl/ShellServerImpl.java (hunk 1 above)
Comment (vietj) [inline src/main/java/io/vertx/ext/shell/impl/ShellServerImpl.java]: error :-)

File: src/main/java/io/vertx/ext/shell/term/impl/ExecCommand.java (hunk 2 above)
Comment (vietj) [inline src/main/java/io/vertx/ext/shell/term/impl/ExecCommand.java]: commands have no input/output, this is executing an SSH cli without a TTY session : in the future if the shell supports redirection, eventually this would be saved in a file or use a file as input : "ssh ... "ls -l > foo.txt"

Comment (tsegismont) [inline src/main/java/io/vertx/ext/shell/term/impl/ExecCommand.java]: Sorry I am not very knowledgeable in this area, but my understanding is
that the user wants to see output when executing something like 'ssh
test@localhost -p 5000 net-ls'

I have been testing the changes, there is no error any more, but indeed no
output.

Do you mean that for now, users can only trigger actions via ssh, but not
provide input or see output?

2016-08-16 19:23 GMT+02:00 Julien Viet <notifications@github.com>:

File: pom.xml [hunk 3]
```diff
@@ -33,7 +33,7 @@
 
   <properties>
     <stack.version>3.4.0-SNAPSHOT</stack.version>
-    <termd.version>1.1.0</termd.version>
+    <termd.version>1.1.2</termd.version>
```
Comment (tsegismont) [inline pom.xml]: I guess this fixes #28 :)

File: src/main/java/io/vertx/ext/shell/term/impl/SSHExecImpl.java [hunk 4]
```diff
@@ -32,58 +32,75 @@
...
+  @Override
+  public Tty stdinHandler(Handler<String> handler) {
+    if (handler != null) {
+      conn.setStdinHandler(codePoints -> {
+        handler.handle(io.termd.core.util.Helper.fromCodePoints(codePoints));
+      });
+    } else {
+      conn.setStdinHandler(null);
+    }
+    return null;
```
Comment (tsegismont) [inline src/main/java/io/vertx/ext/shell/term/impl/SSHExecImpl.java]: Shouldn't this be `return this` ?

Comment (tsegismont) [inline src/main/java/io/vertx/ext/shell/term/impl/SSHExecImpl.java]: Shouldn't this be `return this` ?

**Comment by tsegismont** [comment]
One minor comment otherwise, LGTM

**Comment by tsegismont** [comment]
Thanks @vietj !
